name: Test Build123d Scripts

on:
  pull_request_target: 
    branches:
      - main 
  pull_request:  
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the latest code
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR branch
          repository: ${{ github.event.pull_request.head.repo.full_name }}  # Get forked repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use a compatible Python version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure correct CadQuery version

      - name: Run Build123d Scripts
        run: |
          for script in examples/*.py; do
            echo "Testing $script"
            python "$script" || exit 1  # Stop if any script fails
          done
